//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSDataModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELL_CARRIERS
    {
        public CELL_CARRIERS()
        {
            this.USER_INFO = new HashSet<USER_INFO>();
        }
    
        public int CARRIER_ID { get; set; }
        public string CARRIER_NAME { get; set; }
        public string CARRIER_DOMAIN { get; set; }
    
        public virtual ICollection<USER_INFO> USER_INFO { get; set; }
    }
}
