//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSDataModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINATION
    {
        public DESTINATION()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public string DESTINATION_NAME { get; set; }
        public string DESTINATION_CITY { get; set; }
        public string DESTINATION_STATE { get; set; }
        public string DESTINATION_ZIPCODE { get; set; }
    
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
