//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSDataModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVERS_AVAILABILE_HOURS
    {
        public string USER_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<System.TimeSpan> START_TIME { get; set; }
        public Nullable<System.TimeSpan> END_TIME { get; set; }
    
        public virtual USER_ACCOUNTS USER_ACCOUNTS { get; set; }
    }
}
