//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSDataModel.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDSU_SchoolEntities : DbContext
    {
        public SDSU_SchoolEntities()
            : base("name=SDSU_SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYSTEM_ROLES> SYSTEM_ROLES { get; set; }
        public virtual DbSet<SYSTEM_VARIABLES> SYSTEM_VARIABLES { get; set; }
        public virtual DbSet<USER_ACCOUNTS> USER_ACCOUNTS { get; set; }
        public virtual DbSet<USER_CLAIMS> USER_CLAIMS { get; set; }
        public virtual DbSet<USER_LOGINS> USER_LOGINS { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SYSTEM_LOGS> SYSTEM_LOGS { get; set; }
        public virtual DbSet<DRIVERS_AVAILABILE_HOURS> DRIVERS_AVAILABILE_HOURS { get; set; }
        public virtual DbSet<TRIP> TRIPS { get; set; }
        public virtual DbSet<DESTINATION> DESTINATIONS { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<USER_INFO> USER_INFO { get; set; }
    }
}
