//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSDataModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_ROLES
    {
        public SYSTEM_ROLES()
        {
            this.USER_ROLES = new HashSet<USER_ROLES>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<USER_ROLES> USER_ROLES { get; set; }
    }
}
