//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSDataModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_VARIABLES
    {
        public string VARIABLE_NAME { get; set; }
        public Nullable<int> VARIABLE_VALUE { get; set; }
    }
}
